INSERT INTO TESTDB.PUBLIC.USER (ID, NAME, PASS) VALUES (1, 'Dima', 'MTEx');
INSERT INTO TESTDB.PUBLIC.USER (ID, NAME, PASS) VALUES (2, 'Dasha', 'MTEx');
INSERT INTO TESTDB.PUBLIC.USER (ID, NAME, PASS) VALUES (3, 'Masha', 'MTEx');
INSERT INTO TESTDB.PUBLIC.USER (ID, NAME, PASS) VALUES (4, 'Sasha', 'MTEx');