CREATE TABLE MESSAGE(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  MSG VARCHAR(255));

CREATE TABLE USER(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(50),
  PASS VARCHAR(50));

CREATE TABLE USER_MESSAGE(
  USER_ID INT,
  MSG_ID INT,
  CONSTRAINT USER_MESSAGE_USER_ID_fkey FOREIGN KEY (USER_ID)
  REFERENCES public.USER (id),
  CONSTRAINT USER_MESSAGE_MSG_ID_fkey FOREIGN KEY (MSG_ID)
  REFERENCES public.MESSAGE (ID));

INSERT INTO TESTDB.PUBLIC.USER (ID, NAME, PASS) VALUES (1, 'Dima', 'MTEx');
INSERT INTO TESTDB.PUBLIC.USER (ID, NAME, PASS) VALUES (2, 'Dasha', 'MTEx');
INSERT INTO TESTDB.PUBLIC.USER (ID, NAME, PASS) VALUES (3, 'Masha', 'MTEx');
INSERT INTO TESTDB.PUBLIC.USER (ID, NAME, PASS) VALUES (4, 'Sasha', 'MTEx');